# Copyright 2021 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: secret-patroni-pgsql
  annotations:
    description: |-
      Secret for Patroni Postgresql
    openshift.io/display-name: Secret of Patroni Postgresql
    tags: postgresql
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: ${NAME}
      cluster-name: ${NAME}
    annotations:
      as-copy-of: "template.${NAME}"
    name: ${NAME}
  stringData:
    replication-username: ${PATRONI_REPLICATION_USERNAME}
    replication-password: ${PATRONI_REPLICATION_PASSWORD}
    superuser-username: ${PATRONI_SUPERUSER_USERNAME}
    superuser-password: ${PATRONI_SUPERUSER_PASSWORD}
    app-db-name: ${APP_DB_NAME}
    app-db-username: ${APP_DB_USERNAME}
    app-db-password: ${APP_DB_PASSWORD}
parameters:
  - description: The name of the application for labelling all artifacts.
    displayName: Application Name
    name: NAME
    value: patroni
  - description: Username of the superuser account for initialization.
    displayName: Superuser Username
    name: PATRONI_SUPERUSER_USERNAME
    value: postgres
  #  generate: expression
  #  from: super-[a-zA-Z0-9]{6}
  - description: Password of the superuser account for initialization.
    displayName: Superuser Passsword
    name: PATRONI_SUPERUSER_PASSWORD
    generate: expression
    from: '[a-zA-Z0-9]{32}'
  - description: Username of the replication account for initialization.
    displayName: Replication Username
    name: PATRONI_REPLICATION_USERNAME
    value: replication
  #  generate: expression
  #  from: rep-[a-zA-Z0-9]{6}
  - description: Password of the replication account for initialization.
    displayName: Repication Passsword
    name: PATRONI_REPLICATION_PASSWORD
    generate: expression
    from: '[a-zA-Z0-9]{32}'
  - name: APP_DB_USERNAME
    value: app
  - name: APP_DB_NAME
    value: app
  - name: APP_DB_PASSWORD
    generate: expression
    from: '[a-zA-Z0-9]{32}'
  - name: SUFFIX
    description: A suffix appended to all artifact's name (NAME)
