# Copyright 2021 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# This role binding is meant to allow the Patroni and backup container
# deployment pull image from the tools namespace. Run this policy in
# your tools namespace.
---
kind: Template
apiVersion: v1
metadata:
  name: ${NAME}${SUFFIX}
  annotations:
    description: Deployment template for a nodejs server and postgres db.
    tags: node
    iconClass: icon-node
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        shared: "true"
      name: "${NAME}"
    spec:
      lookupPolicy:
        local: true
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      annotations:
        description: Exposes and load balances the application pods
      labels:
        app: ${NAME}
    spec:
      ports:
        - name: ${PORT}-tcp
          port: ${{PORT}}
          targetPort: ${{PORT}}
      selector:
        deploymentconfig: ${NAME}${SUFFIX}
  - kind: Route
    apiVersion: v1
    metadata:
      name: "${NAME}${SUFFIX}"
      labels:
        app: "${NAME}"
    spec:
      host: "${NAME}${SUFFIX}.${NAMESPACE}.apps.silver.devops.gov.bc.ca"
      port:
        targetPort: ${PORT}-tcp
      path: ''
      to:
        kind: Service
        name: "${NAME}${SUFFIX}"
        weight: 100
      tls:
        termination: edge
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        app: ${NAME}
      annotations:
        description: Defines how to deploy the application server
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}${SUFFIX}
            from:
              kind: ImageStreamTag
              name: "${NAME}:${VERSION}"
        - type: ConfigChange
      replicas: 1
      selector:
        name: ${NAME}${SUFFIX}
      template:
        metadata:
          name: ${NAME}${SUFFIX}
          labels:
            name: ${NAME}${SUFFIX}
            app: ${NAME}
        spec:
          containers:
            - name: ${NAME}${SUFFIX}
              image: " "
              ports:
                - name: ${NAME}
                  containerPort: ${{PORT}}
                  protocol: TCP
#              livenessProbe:
#                failureThreshold: 3
#                httpGet:
#                  path: /
#                  port: ${{PORT}}
#                  scheme: HTTP
#                initialDelaySeconds: 60
#                periodSeconds: 10
#                successThreshold: 1
#                timeoutSeconds: 3
#              readinessProbe:
#                failureThreshold: 3
#                httpGet:
#                  path: /
#                  port: ${{PORT}}
#                  scheme: HTTP
#                initialDelaySeconds: 25
#                periodSeconds: 10
#                successThreshold: 1
#                timeoutSeconds: 2
              resources:
                requests:
                  memory: 256Mi
                  cpu: 10m
                limits:
                  memory: 512Mi
                  cpu: 50m
              env:
                - name: PORT
                  value: ${PORT}
                - name: MONGODB_URI
                  value: "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_URL}:27017"
                - name: MONGODB_DB_MAIN
                  value: ${MONGODB_DB_MAIN}
parameters:
  - name: PORT
    required: true
    value: "8080"
    description: service open port
  - name: NAME
    required: true
    value: hwp-server
  - name: NAMESPACE
    required: true
  - name: MONGODB_USER
    required: true
  - name: MONGODB_PASSWORD
    required: true
  - name: MONGODB_URL
    required: true
  - name: MONGODB_DB_MAIN
    required: true
  - name: VERSION
    required: true
    description: version as an image tag
  - name: SUFFIX
    required: false
    description: version as an image tag
