version: 2
updates:
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "./"
    open-pull-requests-limit: 4
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "13:00"
  - package-ecosystem: "npm"
    directory: "./app/client"
    open-pull-requests-limit: 4
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "13:00"
  - package-ecosystem: "npm"
    directory: "./app/server"
    open-pull-requests-limit: 4
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "13:00"
