version: "3.7"
services:
  #############################################################################################
  ###                                     MONGO DB                                          ###
  #############################################################################################
  mongodb:
    image: "mongo:4"
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME:-TheNeighbourhood}
    volumes:
      - ./mongo/init:/docker-entrypoint-initdb.d
      - ./mongo/init/data:/tmp/data
      - ./mongo/data:/data/db
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    networks:
      - hwp-network
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u ${MONGO_ROOT_USERNAME} -p ${MONGO_ROOT_PASSWORD} --quiet | grep 1
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 120s

  #############################################################################################
  ###                                     React Frontend                                    ###
  #############################################################################################
  hwp-frontend:
    container_name: hwp-frontend
    build:
      context: .
      dockerfile: ./app/client/Dockerfile
      args:
        env: ${ENV_FILE:-.env-template}
    networks:
      - hwp-network
    ports:
      - ${FRONTEND_PORT:-8080}:${FRONTEND_PORT:-8080}
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules

  #############################################################################################
  ###                                     Express API                                       ###
  #############################################################################################
  hwp-api:
    container_name: hwp-api
    tty: true
    build:
      context: .
      dockerfile: ./app/server/docker/dev/Dockerfile
      args:
        env: ${ENV_FILE:-.env-template}
    networks:
      - hwp-network
    ports:
      - ${REACT_APP_API_PORT:-5000}:${REACT_APP_API_PORT:-5000}
    volumes:
      - .:/usr/src/
    command: >
      sh -c "cp /usr/src/.env /usr/src/app/server/.env &&
      npm --prefix /usr/src/app/server ci --only-production &&
      nodemon -L /usr/src/app/server/index.js"
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: curl localhost:${REACT_APP_API_PORT:-5000} | grep 'Node.js Server is live!'
      interval: 20s
      timeout: 30s
      retries: 10
      start_period: 120s

networks:
  hwp-network:
    driver: "bridge"
