version: "3.7"
services:
  #############################################################################################
  ###                                     MONGO DB                                          ###
  #############################################################################################
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-admin}
    volumes:
      - mongo-volume:/data/db
    ports:
      - 27017:27017
    networks:
      - hwp-network

  #############################################################################################
  ###                                     React Frontend                                    ###
  #############################################################################################
  hwp-frontend:
    container_name: hwp-frontend
    build:
      context: ./app/client
    networks:
      - hwp-network
    ports:
      - 8080:8080

  #############################################################################################
  ###                                     Express API                                       ###
  #############################################################################################
  hwp-api:
    container_name: hwp-api
    build:
      context: ./app/server
    networks:
      - hwp-network
    ports:
      - 5000:5000
      
networks:
  hwp-network:
    driver: "bridge"
    
volumes:
  mongo-volume:
