version: "3.7"
services:
  mongodb:
    image: "mongo:4"
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME:-TheNeighbourhood}
    volumes:
      - ./mongo/init:/docker-entrypoint-initdb.d
      - ./mongo/init/data:/tmp/data
      - ./mongo/data:/data/db
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    networks:
      - hwp-network
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u ${MONGO_ROOT_USERNAME} -p ${MONGO_ROOT_PASSWORD} --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  hwp-frontend-dev:
    container_name: hwp-frontend-dev
    build:
      context: .
      dockerfile: ./app/client/Dockerfile.dev
      target: development
      args:
        NODE_ENV: development
        env: ${ENV_FILE:-.env-template}
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - ${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}
    networks:
      - hwp-network

  hwp-api:
    container_name: hwp-api
    build:
      context: .
      dockerfile: ./app/server/Dockerfile
      args:
        env: ${ENV_FILE:-.env-template}
    networks:
      - hwp-network
    ports:
      - ${REACT_APP_API_PORT:-5000}:${REACT_APP_API_PORT:-5000}
    volumes:
      - .:/usr/src/app/
    command: nodemon -L /usr/src/app/app/server/index.js
    depends_on:
      mongodb:
        condition: service_healthy

networks:
  hwp-network:
    driver: "bridge"
