version: "3.7"
services:
  #############################################################################################
  ###                                     MONGO DB                                          ###
  #############################################################################################
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=root-db
    volumes:
      - ./init-mongodb:/docker-entrypoint-initdb.d
      - ./init-mongodb/data:/tmp/data
    ports:
      - 27017:27017
    networks:
      - hwp-network

  #############################################################################################
  ###                                     React Frontend                                    ###
  #############################################################################################
  hwp-frontend:
    container_name: hwp-frontend
    build:
      context: ./
      dockerfile: ./app/client/Dockerfile
    networks:
      - hwp-network
    ports:
      - 80:80

  #############################################################################################
  ###                                     Express API                                       ###
  #############################################################################################
  hwp-api:
    env_file: .env
    container_name: hwp-api
    build:
      context: ./app/server
    networks:
      - hwp-network
    ports:
      - 5000:5000
    depends_on:
      - mongodb

networks:
  hwp-network:
    driver: "bridge"
