version: "3.7"
services:
#############################################################################################
###                                     MONGO DB                                          ###
#############################################################################################
mongodb:
  image: 'mongo:latest'
  container_name: 'mongodb'
  environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-admin}
  volumes:
    - mongo-volume:/data/db
  ports:
    - 27017:27017
  networks:
    -chw-network

networks:
  chw-network:
    driver: "bridge"
    
volumes:
  mongo-volume:
