version: "3.7"
services:
  #############################################################################################
  ###                                     MONGO DB                                          ###
  #############################################################################################
  mongodb:
    image: "mongo:latest"
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./mongo/init:/docker-entrypoint-initdb.d
      - ./mongo/init/data:/tmp/data
      - ./mongo/data:/data/db
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    networks:
      - hwp-network

  #############################################################################################
  ###                                     React Frontend                                    ###
  #############################################################################################
  hwp-frontend:
    container_name: hwp-frontend
    build:
      context: .
      dockerfile: ./app/client/Dockerfile
      args:
        env: ${ENV_FILE:-.env-template}
    networks:
      - hwp-network
    ports:
      - ${FRONTEND_PORT:-8080}:${FRONTEND_PORT:-8080}
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules

  #############################################################################################
  ###                                     Express API                                       ###
  #############################################################################################
  hwp-api:
    container_name: hwp-api
    build:
      context: .
      dockerfile: ./app/server/Dockerfile
      args:
        env: ${ENV_FILE:-.env-template}
    networks:
      - hwp-network
    ports:
      - ${API_PORT:-5000}:${API_PORT:-5000}
    volumes:
      - .:/usr/src/app/
    command: nodemon -L /usr/src/app/app/server/index.js
    depends_on:
      - mongodb

networks:
  hwp-network:
    driver: "bridge"
