version: "3.7"
services:
  #############################################################################################
  ###                                     MONGO DB                                          ###
  #############################################################################################
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./mongo/init:/docker-entrypoint-initdb.d
      - ./mongo/init/data:/tmp/data
      - ./mongo/data:/data/db
    ports:
      - 27017:27017
    networks:
      - hwp-network

  #############################################################################################
  ###                                     React Frontend                                    ###
  #############################################################################################
  hwp-frontend:
    container_name: hwp-frontend
    build:
      context: ./
      dockerfile: ./app/client/Dockerfile
      args:
        env: ${ENV_FILE_REACT:-.env-template}
    networks:
      - hwp-network
    ports:
      - 80:8080

  #############################################################################################
  ###                                     Express API                                       ###
  #############################################################################################
  hwp-api:
    environment:
      - MONGO_URI=${MONGO_URI}
    container_name: hwp-api
    build:
      context: ./app/server
    networks:
      - hwp-network
    ports:
      - 5000:5000
    depends_on:
      - mongodb

networks:
  hwp-network:
    driver: "bridge"
