// Used to initialize the options collection in the database
const options = [
  {
    component: "registration",
    options: {
      passwordMinLength: 8,
      passwordMaxLength: 250,
      usernameMinLength: 3,
      usernameMaxLength: 20,
      usernameDisallowedStrings: [
        "www.",
        ".com",
        ".org",
        ".net",
        ".io",
        ".ca",
        ".us",
        ".uk",
        ".co",
      ],
    },
  },
  {
    component: "post",
    options: {
      titleMinLength: 3,
      titleMaxLength: 50,
      titleDisallowedCharacters: "\\\\/@\\*\\^_\\+-=`~\\]\\[{}:;<>",
      titleDisallowedStrings: [
        "www.",
        ".com",
        ".org",
        ".net",
        ".io",
        ".ca",
        ".us",
        ".uk",
        ".co",
      ],
      messageMinLength: 3,
      messageMaxLength: 40000,
      createPostEngagementWeight: 5,
    },
  },
  {
    component: "community",
    options: {
      titleMinLength: 3,
      titleMaxLength: 25,
      titleDisallowedCharacters: "\\\\/@\\*\\^_\\+-=`~\\]\\[{}:;<>",
      titleDisallowedStrings: [
        "www.",
        ".com",
        ".org",
        ".net",
        ".io",
        ".ca",
        ".us",
        ".uk",
        ".co",
      ],
      descriptionMinLength: 0,
      descriptionMaxLength: 300,
      tagMinLength: 3,
      tagMaxLength: 16,
      tagDescriptionMinLength: 0,
      tagDescriptionMaxLength: 200,
      ruleMinLength: 3,
      ruleMaxLength: 50,
      ruleDescriptionMinLength: 0,
      ruleDescriptionMaxLength: 200,
      createCommunityEngagementWeight: 0,
    },
  },
  {
    component: "comment",
    options: {
      messageMinLength: 1,
      messageMaxLength: 1000,
      createCommentEngagementWeight: 1,
    },
  },
  {
    component: "user",
    options: {
      firstNameMinLength: 2,
      firstNameMaxLength: 30,
      lastNameMinLength: 2,
      lastNameMaxLength: 30,
      bioMinLength: 1,
      bioMaxLength: 300,
      titleMinLength: 1,
      titleMaxLength: 55,
      organizationMinLength: 2,
      organizationMaxLength: 55,
      interestMinLength: 1,
      interestMaxLength: 16,
    },
  },
  {
    component: "flags",
    options: {
      flags: [
        "Inappropriate",
        "Hate",
        "Harassment or Bullying",
        "Spam",
        "Misinformation",
        "Against Community Rules",
      ],
    },
  },
  {
    component: "notifications",
    options: {
      frequencies: ["none", "immediate", "daily", "weekly", "monthly"],
    },
  },
];

module.exports = options;
