#This is a basic workflow to help you get started with Actions

name: clean

# Controls when the action will run. 
on:
  pull_request:
    branches: ['main', 'release/**']
    types: ['closed']
  
defaults:
  run:
    working-directory: ./app

jobs:

  clean-build-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/.pipeline
    steps:

      # Build the image using the specified build config
      # Get its build ID
      # Get the commit ID of that build
      # Get the SHA256 signature of the image
      # Tag the image with the commit ID and "dev"
      # ------------------------------------------------

      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Clean the Build and Dev Namespace
        run: |
          oc version
          oc login --token=${{ secrets.OPENSHIFT_TOKEN}} --server=${{ secrets.OPENSHIFT_SERVER_URL }}
          npm ci
          DEBUG=* npm run clean -- --pr=${{ github.event.pull_request.number }} --env=build --git.branch.name=${{github.head_ref}} --git.ref=${{github.head_ref}}
          DEBUG=* npm run clean -- --pr=${{ github.event.pull_request.number }} --env=dev --git.branch.name=${{github.head_ref}} --git.ref=${{github.head_ref}}
 
